### ISSUE TITLE
Hackathon DAO | 22S1 grant potential applicants support

### ISSUE THREAD

**Issue by momohou21** [dorahacksglobal/Hackathon-Playbook#13]
Support applicants onboarding Hackathon DAO grant from 2021-12-24 and 2022-02-21, including

- Grant content review
- Grant email draft and reaching out
- Discord maintainess
    - FAQ on apply instructions on our discord / Telegram / wechat group
    - Grant updates including new BUIDL online, voting progress, voting results, etc.

**Bounty: 200 USDT**

Discord 👉 https://discord.gg/gVBYGfmwQv
Contact @momo_hou for bounty details

**Comment by momohou21** [comment]
#23

**Comment by momohou21** [comment]
#23

**Comment by momohou21** [comment]
Please add a PR to edit this file https://dorahacksglobal.github.io/Hackathon-Playbook/playground/2021/11/10/bounties.html for this bounty

**Comment by sputnik-meng** [comment]
#13
