### ISSUE TITLE
hackathon DAO | ZK Knowledge repo architect

### ISSUE THREAD

**Issue by momohou21** [dorahacksglobal/Hackathon-Playbook#14]
Build up the structure of ZK knowledge repo on our playbook. The ideal structure may include and not limited to:
- What is ZK?
- Key concepts
- Current solutions and measurement
- Applications
- References

**Bounty: 300 USDT + 3 $HAC**

**Instructions**
- Join our [Discord](https://discord.gg/gVBYGfmwQv) 
- Go to **#💰bounties channel** 
- Send “**ZK Knowledge repo architect**” and our staff will follow up with you bounty details and reviewing.
- The bonus will be released after the first PR of the architect PR merges.

**Comment by Abuchtela** [comment]
> Build up the structure of ZK knowledge repo on our playbook. The ideal structure may include and not limited to:
> 
> * What is ZK?
> * Key concepts
> * Current solutions and measurement
> * Applications
> * References
> 
> **Bounty: 300 USDT + 3 $HAC**
> 
> **Instructions**
> 
> * Join our [Discord](https://discord.gg/gVBYGfmwQv)
> * Go to **#💰bounties channel**
> * Send “**ZK Knowledge repo architect**” and our staff will follow up with you bounty details and reviewing.
> * The bonus will be released after the first PR of the architect PR merges.

**ZK Knowledge repo architect**
