### ISSUE TITLE
Hackathon DAO | ZK architect referral

### ISSUE THREAD

**Issue by momohou21** [dorahacksglobal/Hackathon-Playbook#20]
Refer a solid ZK professional to build our ZK knowledge repo structure on Hackathon Playbook.

**Bounty: 100 USDT + 1 $HAC**

**Instructions**
- Join our [Discord](https://discord.gg/gVBYGfmwQv) 
- Go to **#💰bounties channel** 
- Send “**ZK architecture referral**” and our staff will follow up with you bounty details and reviewing.
- The bonus will be released after the first PR of the referee merged. 

Related bounty: https://hackerlink.io/bounty/60

**Comment by momohou21** [comment]
Please add a PR to edit this file https://dorahacksglobal.github.io/Hackathon-Playbook/playground/2021/11/10/bounties.html for this bounty

**Comment by DhunterAO** [comment]
#24

**Comment by momohou21** [comment]
#52
