### ISSUE TITLE
Hackathon DAO | zk repo - understanding zkRollup PartII

### ISSUE THREAD

**Issue by momohou21** [dorahacksglobal/Hackathon-Playbook#33]
Participate in podcast to help people understand detailed tech design for zkRollup, including proof generation and off-chain verification.

**Bounty: 100 USDT + 1 $HAC**

**Instructions**
- Join our [Discord](https://discord.gg/gVBYGfmwQv) 
- Go to **#💰bounties channel** 
- Send “**zk repo - understanding Bulletproof**” and our staff will follow up with you bounty details and reviewing.
- The bonus will be released after the first PR of the referee merged.

**Comment by sputnik-meng** [comment]
#33
