### ISSUE TITLE
hackathon DAO | ZK Podcast - deep dive into zkRollup 

### ISSUE THREAD

**Issue by momohou21** [dorahacksglobal/Hackathon-Playbook#35]
To be the main guest speaker of a podcast about zkRollup. The estimated length of the podcast post-editing would be 1-1.5 hour(s) and it should include but not limited to:
- Deep dive into zkrollup's proof generation

**Bounty: 100 USDT + 1 $HAC**

**Instructions**
- Join our [Discord](https://discord.gg/gVBYGfmwQv) 
- Go to **#💰bounties channel** 
- Send “**zkRollup Podcast**” and our staff will follow up with you bounty details and reviewing.
- The bonus will be released after the first PR of the podcast publishing.

**Comment by sputnik-meng** [comment]
#35
